### ISSUE TITLE
Alternate configurations need work[GENERAL]

### ISSUE THREAD

**Issue by raer0** [raer0/containarr#29]
# Issue:

Alternate configurations are an afterthought. I've identified some improvements that could be made:

- create a build process for alternate configurations that uses the main docker-compose.yml file as a template
- create "snippets" of alternate configurations as .yml files to be placed inside of ```service:``` (i actually don't know what to call the part of the docker-compose.yml that 'service:' represents so if someone is reading this and does, please let me know)
- build each alt config after code review before merging PR.

**Comment by ray-rock** [comment]
# another huge oversight
The build process for alt configs does not support the reverse proxy AT ALL. And this isn't documented either, so anyone using alt configs is kinda left to figure out wtf is going on.
